# Generated by Django 3.0.8 on 2020-08-14 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200814_1047'),
        ('account', '0003_auto_20200813_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.Level', verbose_name='Level'),
            preserve_default=False,
        ),
    ]
